services:
  backend:
    build:
      context: .
    command: uvicorn src.predict:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front-end
    ports:
      - "8501:8501"