stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - data/raw/Telco_Customer_Churn.csv
      - src/prepare_data.py
    outs:
      - data/processed/train.csv
      - data/processed/test.csv
      - models/preprocessor.pkl
  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - data/processed/test.csv
      - models/preprocessor.pkl
      - src/train.py
    outs:
      - models/churn_prediction_model.pkl
    metrics:
      - metrics/train_metrics.json