#name: CI Pipeline

#on: [push]

#jobs:
 # build:
  #  runs-on: ubuntu-latest
   # steps:
    #- uses: actions/checkout@v3
    #- name: Set up Python
     # uses: actions/setup-python@v4
     # with:
      #  python-version: '3.10'
    #- name: Install dependencies
     # run: |
      #  python -m pip install --upgrade pip
       # pip install -r requirements.txt
       # pip install dvc
   # - name: Initialize DVC
    #  run: |
    #    dvc init --no-scm
     #   #dvc remote add -d myremote s3://my-bucket/churn-mlops  # استبدل بمسارك إذا عندك S3
   # - name: Pull DVC data
    #  run: dvc pull
   # - name: Run evaluate script
   #   run: python src/evaluate.py
   # - name: Build and test
    #  run: |
     #   docker-compose up --build
name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install joblib pandas scikit-learn fastapi
    - name: Run evaluate script
      run: python src/evaluate.py
    - name: Build and test
      run: |
        docker-compose up --build