name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up DVC
      uses: iterative/setup-dvc@v1
      with:
        dvc-version: '3.61.0' 

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc

    - name: Pull DVC data
      run: dvc pull

    - name: Run evaluate script
      run: python src/evaluate.py
    
    # - name: Build and test
    #   run: |
    #     docker-compose up --build